name: Davis AI, AI Resources Wesbsite
tagline: AI RESOURCES WEBSITE 
# date: October 2023
citation_date: October 2023
proceedings_title: Proceedings of the First MiniCon Conference
analytics: UA-
logo:
  image: static/images/DavisAILogoNoBg2.png
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'AI Resources Website'
  separator: ': '
background_image: static/images/main.jpg
organization: Davis Institute for Artificial Intelligence

# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com
